language: go

go:
  - "1.11"

services:
  - docker

go_import_path: github.com/pmorelli92/go-state-machine-two/

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

jobs:
  include:
    - stage: test
      if: type == pull_request
      script: make test
      env:
        - GO111MODULE=on

    - stage: test_and_cover
      name: "Test (with coverage)"
      if: type != pull_request
      script:
        - go test -v -covermode=count -coverprofile=coverage.out ./...
        - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
      env:
        - GO111MODULE=on