language: go

go:
  - "1.11"

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

jobs:
  include:
    - stage: test_and_cover
      name: "Test (with coverage)"
      script:
        - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN